genshinforum/genshinapp/urls.py
from django.contrib import admin
from django.urls import path
from genshinapp.views import *
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', index, name='main'),
    path('themes/', themes, name='themes'),
    path('reg/', reg, name='reg'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/',logout_view,name='logout'),
    path('themes/<int:theme_id>', themesinside, name='insidetheme'),
]

genshinforum/genshinforum/urls.py
from django.contrib import admin
from django.urls import path
from genshinapp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', index, name='main'),
    path('themes/', themes, name='themes'),
    path('reg/', reg, name='reg'),
    path('themes/<int:theme_id>', themesinside, name='insidetheme'),
]

genshinforum/genshinapp/models.py
from django.db import models
from ckeditor.fields import RichTextField
import datetime
from django.contrib.auth import get_user_model
# Create your models here.
class Themes(models.Model):
    id = models.BigAutoField(primary_key=True)
    themename = models.TextField()
    themecontent = RichTextField()
    themeimg = models.ImageField(upload_to='img/')

    class Meta():
        verbose_name = "Тема"
        verbose_name_plural = "Темы"

    def __str__(self):
        return self.themename

class Comments(models.Model):
    id = models.BigAutoField(primary_key=True)
    commentcontent = RichTextField()
    comment_date = models.DateField(default=datetime.date.today, blank=True, null=True)
    commentimg = models.ImageField(upload_to='img/')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, null=True)
    theme = models.ForeignKey(Themes, on_delete=models.CASCADE, blank=True, null=True)

genshinforum/genshinapp/forms.py
from django import forms
from .models import *
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
class ThemesForm(forms.ModelForm):
    class Meta:
        model = Themes
        fields = '__all__'

class RegForm(forms.ModelForm):
    username = forms.CharField(label="Логин")
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'nickname': 'Прозвище',
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Пароли не совпадают!")
        return cd['password2']
    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

class LoginUserForm(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['commentcontent','commentimg']

genshinforum/genshinapp/views.py
from django.shortcuts import render, redirect
from .forms import *

def index(request):
    return render(request, 'genshinapp/index.html')

def themes(request):
    if request.method == 'POST':
        form = ThemesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('../themes')
    else:
        form = ThemesForm()
    themes = Themes.objects.all()
    data = {
        'themes':themes,
    }
    return render(request, 'genshinapp/themes.html', data)

def reg(request):
    return render(request, 'genshinapp/reg.html')
def themesinside(request, theme_id):
    themes = Themes.objects.filter(id=theme_id)
    data = {
        'themes': themes,
    }
    return render(request,'genshinapp/insidethemes.html', data)

genshinforum/genshinforum/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.urls import reverse_lazy
def index(request):
    return render(request, 'genshinapp/index.html')

def themes(request):
    if request.method == 'POST':
        form = ThemesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('../themes')
    else:
        form = ThemesForm()
    themes = Themes.objects.all()
    data = {
        'themes':themes,
    }
    return render(request, 'genshinapp/themes.html', data)

def reg(request):
    if request.method == 'POST':
        form = RegForm(request.POST)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.save()
            return redirect('../main')
    else:
        form = RegForm()
    data = {
        'form':form,
    }
    return render(request, 'genshinapp/reg.html', data)
def themesinside(request, theme_id):
    themes = Themes.objects.filter(id=theme_id)
    data = {
        'themes': themes,
    }
    return render(request,'genshinapp/insidethemes.html', data)

def logout_view(request):
    logout(request)
    return redirect('../main')
class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'genshinapp/login.html'
    extra_context = {'title': "Авторизация"}

    def get_success_url(self):
        return reverse_lazy('main')

genshinforum/genshinapp/templates/genshinapp/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css'%}">
	<title>{% block title %}Форум по игре Genshin Impact | Главная страница{% endblock title %}</title>
	<link rel="stylesheet" href="{% static 'js/bxslider/dist/jquery.bxslider.css'%}">
	<script src="https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js"></script>
</head>
<body>
	<div class="header">
		<div class="logo">
		<a href="{% url 'main' %}"><img src="{%static 'img/loho.png'%}" alt=""></a>
	</div>
		<div class="header_buts">
			<ul>
				<li>
					<p> <a href="{% url 'main' %}">ГЛАВНАЯ</a></p>
				</li>
			</ul>
		</div>
		<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'themes' %}">ТЕМЫ</a></p>
				</li>
			</ul>
		</div>

		<div class="profile">
			{% if user.is_authenticated %}
			<div class="profile_nick">
				<div class="profile_img">
				<img src="{% static 'img/Pimon.png' %}" alt="Аватар пользователя">
				</div>
				<p><a href="">{{user.username}}</a></p> <a href="{% url 'logout' %}">Выйти</a>
			</div>
			{% else %}
			<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'reg' %}"	>РЕГИСТРАЦИЯ</a></p>
				</li>
			</ul>
			</div>
			<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'login' %}">ВХОД</a></p>
				</li>
			</ul>
			</div>
			{% endif %}
		</div>
	</div>
	{% block container %}
	<div class="container">
		<div class="maintxt">
			<img src="{%static 'img/glogo.png'%}" alt="">
		</div>
		<div class="description">
			{% block description %}
			<div class="aboutforum">
				<p>Genshin Impact, — это китайская условно-бесплатная онлайн-игра, которая в 2020 году разорвала интернет и стала настоящим подростковым хитом. По сюжету, брат и сестра застревают в волшебном мире и теряют друг друга. На этом и построена завязка: игроку нужно найти потерянного брата либо сестру. Но заниматься этим сразу необязательно. Почему? Потому что перед игроком открывается огромный мир под названием Тейват, поделённый на семь регионов — в каждом своя культура, персонажи и даже своя кухня. На данный момент в игре доступны всего 5 регионов - Мондштадт, Ли Юэ, Инадзума, Сумеру и Фонтейн.</p>
			</div>
			{% endblock description %}
		</div>
		<div class="sliderblock">
				<div class="slider">
					<div><img src="{% static 'img/mond.png' %}" alt=""></div>
					<div><img src="{% static 'img/li.png' %}" alt=""></div>
					<div><img src="{% static 'img/inadzuma.png' %}" alt=""></div>
					<div><img src="{% static 'img/sumeru.png' %}" alt=""></div>
					<div><img src="{% static 'img/fontaine.png' %}" alt=""></div>
				</div>
		</div>
	</div>
	{% endblock container %}
	<div class="container1">
		{% block container1 %}
		<div class="regtxt">
			<p>Ты никогда не играл в геншин? Зарегистрируйся прямо сейчас!</p>
		</div>
		<div class="regimg">
			<a href="https://genshin.hoyoverse.com/pre-register/"> <img src="{% static 'img/regimg.png' %}"></a>
		</div>
		{% endblock container1 %}
	</div>
	{% block script %}
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script src="{% static 'js/bxslider/dist/jquery.bxslider.min.js' %}"></script>
		<script src="{% static 'js/slider.js' %}"></script>
		<script src="{% static 'js/script.js' %}"></script>
	{% endblock script %}
</body>
</html>

genshinforum/genshinapp/templates/genshinapp/insidethemes.html
{% extends 'genshinapp/index.html' %}
{% load static%}

{% block title %} {% for i in themes %} {{i.themename}} {% endfor %} {% endblock title %}

{% block container %}

<div class="containertheme1">
    <div class="theme1">
        {% for i in themes%}
        <p>{{i.themename|safe}}</p>
        {% endfor %}
    </div>
    <div class="theme2">
        {% for s in themes%}
        {{s.themecontent|safe}}
        <img src="/static/img/{{s.themeimg}}" alt="">
        {% endfor %}
    </div>
            <div class="commentaries" id="commentaries">
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
<!--                    {{ form.as_p }}-->
					<label for="commentcontent">Содержание комментария:</label>
					<textarea name="commentcontent" id="commentcontent" cols="30" rows="10">
					</textarea>
					<label for="id_commentimg" id="themeimg">Загрузить изображение:</label>
					<input name="commentimg" type="file" id="id_commentimg">
					<br>
    			<button class="button" onclick="sendText()">Submit text</button>
				</form>
                {% for i in comments %}
                <div class="coment">
                    <p class="coment_p">{{i.user}}
                    {{i.comment_date}}</p>
                    {{i.commentcontent | safe}}
                    <img src="/static/img/{{i.commentimg}}" alt="">
                </div>
                {% endfor %}
			</div>
</div>
{% endblock container %}
{% block script %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock script %}

{% block container1 %}{% endblock container1 %}

genshinforum/genshinapp/templates/genshinapp/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css'%}">
	<title>{% block title %}Форум по игре Genshin Impact | Главная страница{% endblock title %}</title>
	<link rel="stylesheet" href="{% static 'js/bxslider/dist/jquery.bxslider.css'%}">
</head>
<body>
	<div class="header">
		<div class="logo">
		<a href="{% url 'main' %}"><img src="{%static 'img/loho.png'%}" alt=""></a>
	</div>
		<div class="header_buts">
			<ul>
				<li>
					<p> <a href="#">ГЛАВНАЯ</a></p>
				</li>
			</ul>
		</div>
		<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'themes' %}">ТЕМЫ</a></p>
				</li>
			</ul>
		</div>

		<div class="profile">
			{% if user.is_authenticated %}
			<div class="profile_nick">
				<div class="profile_img">
				<img src="{% static 'img/Pimon.png' %}" alt="Аватар пользователя">
				</div>
				<p><a href="">{{user.username}}</a></p> <a href="{% url 'logout' %}">Выйти</a>
			</div>
			{% else %}
			<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'reg' %}"	>РЕГИСТРАЦИЯ</a></p>
				</li>
			</ul>
			</div>
			<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'login' %}">ВХОД</a></p>
				</li>
			</ul>
			</div>
			{% endif %}
		</div>
	</div>
    <div class="logincon">
        <div class="loginwindow">
			<form method="post">
				{% csrf_token %}
				<label for="username">Логин:</label>
				<input type="text" name="username" id="username">
				<label for="password">Пароль</label>
				<input type="password" name="password" id="password">
				<button type="submit"> Войти :)</button>
			</form>
		</div>
    </div>
</body>
</html>

genshinforum/genshinapp/templates/genshinapp/reg.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css'%}">
	<link rel="stylesheet" href="{% static 'js/bxslider/dist/jquery.bxslider.css'%}">
	<title>Форум по игре Genshin Impact | Главная страница</title>

</head>
<body>
	<div class="header">
		<div class="logo">
		<a href="{% url 'main' %}"><img src="{%static 'img/loho.png'%}" alt=""></a>
	</div>
		<div class="header_buts">
			<ul>
				<li>
					<p> <a href="{% url 'main' %}">ГЛАВНАЯ</a></p>
				</li>
			</ul>
		</div>
		<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'themes' %}">ТЕМЫ</a></p>
				</li>
			</ul>
		</div>
		<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'reg' %}">РЕГИСТРАЦИЯ</a></p>
				</li>
			</ul>
		</div>
		<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'login' %}">ВХОД</a></p>
				</li>
			</ul>
		</div>
		<div class="profile">
			<div class="profile_nick">
				<p>ПСЕВДОНИМ</p>
			</div>
			<div class="profile_img">
				<img src="{% static 'img/Pimon.png' %}" alt="Аватар пользователя">
			</div>
		</div>
	</div>
	<div class="regwindowcon">	
		<div class="regwindow">
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit"> Зарегистрироваться :)</button>
<!--			<label for="username">Логин:</label>-->
<!--			<input type="text" name="username" id="username">-->
<!--			<label for="email">E-mail:</label>-->
<!--			<input type="email" name="email" id="email">-->
<!--			<label for="password">Пароль</label>-->
<!--			<input type="password" name="password" id="password">-->
<!--			<button type="submit"> Зарегистрироваться :)</button>-->
		</form>
	</div>	
	</div>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="{% static 'js/bxslider/dist/jquery.bxslider.min.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>
</body>
</html>

genshinforum/genshinapp/templates/genshinapp/themes.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css'%}">
	<link rel="stylesheet" href="{% static 'js/bxslider/dist/jquery.bxslider.css'%}">
	<title>Форум по игре Genshin Impact | Главная страница</title>
	<script src="https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js"></script>
</head>
<body>
	<div class="header">
		<div class="logo">
		<a href="{% url 'main' %}"><img src="{%static 'img/loho.png'%}" alt=""></a>
	</div>
		<div class="header_buts">
			<ul>
				<li>
					<p> <a href="{% url 'main' %}">ГЛАВНАЯ</a></p>
				</li>
			</ul>
		</div>
		<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'themes' %}">ТЕМЫ</a></p>
				</li>
			</ul>
		</div>
		<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'reg' %}">РЕГИСТРАЦИЯ</a></p>
				</li>
			</ul>
		</div>
		<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'login' %}">ВХОД</a></p>
				</li>
			</ul>
		</div>
		<div class="profile">
			{% if user.is_authenticated %}
			<div class="profile_nick">
				<div class="profile_img">
				<img src="{% static 'img/Pimon.png' %}" alt="Аватар пользователя">
				</div>
				<p><a href="">{{user.username}}</a></p> <a href="{% url 'logout' %}">Выйти</a>
			</div>
			{% else %}
			<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'reg' %}"	>РЕГИСТРАЦИЯ</a></p>
				</li>
			</ul>
			</div>
			<div class="header_buts">
			<ul>
				<li>
			<p> <a href="{% url 'login' %}">ВХОД</a></p>
				</li>
			</ul>
			</div>
			{% endif %}
		</div>
	</div>
    <div class="containerthemes">
		<div class="cancelthemeblock" id="cancelthemeblock">
			<img src="{% static 'img/krest.png' %}" alt="">
		</div>
		<div class="themebut" id="open">
			<a class="myButton" href="#">Создать тему</a>
		</div>
			<div class="themeblock" id="themeblock">
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<label for="themename" id="themename">Название темы:</label>
					<input type="text" name="themename" placeholder="Название вашей темы">
					<label for="themecontent">Содержание:</label>
					<textarea name="themecontent" id="themecontent" cols="30" rows="10">
					</textarea>
					<label for="themeimg" id="themeimg">Загрузить изображение:</label>
					<input name="themeimg" type="file">
					<br>
    			<button class="button" onclick="sendText()">Submit text</button>
				</form>cd
			</div>
				<div class="themebox">
					{% for s in themes%}
					<div class="themeсont">
						<a href="{% url 'insidetheme' s.pk %}">{{s.themename}}</a>
						<img src="/static/img/{{s.themeimg}}">
					</div>
					{% endfor %}
				</div>
			</div>
			<script src="{% static 'js/script.js' %}"></script>	
	</body>
</html>